#!/usr/bin/env bash

# selvbetjening.aarhuskommune.dk branch
# Setup upstream with OS2Web Datalookup
git remote add upstream https://github.com/OS2web/os2web_datalookup.git
git fetch
git reset --hard 3.3.1
git merge --no-ff origin/feature/fetch-first-middle-and-last-name
git checkout --theirs CHANGELOG.md
git add CHANGELOG.md
git commit -m "Merge remote-tracking branch 'origin/feature/fetch-first-middle-and-last-name' into selvbetjening.aarhuskommune.dk"

docker run --rm --volume .:/app itkdev/php8.4-fpm:latest sed --in-place '1i This is a hack so the CHANGELOG is messed up. \nGenerated by build_release.sh' CHANGELOG.md
git add CHANGELOG.md
git commit -m "Updated CHANGELOG"
